### ISSUE TITLE
Twitch pages not loading

### ISSUE THREAD

**Issue by sowind** [nomomo/Twitch-Auto-Max-Quality#1]
Hello.
A few days ago, the twitch pages stopped opening (infinite loading) due to a problem with the jQuery protocol.
![image](https://user-images.githubusercontent.com/7592081/110606950-86271b80-81ac-11eb-9c54-474bb8698e0f.png)

**Comment by nomomo** [comment]
Thanks for your contribution, it has been merged into version 0.0.7.
