### ISSUE TITLE
"Only source quality method" doesn't work on VOD anymore

### ISSUE THREAD

**Issue by asherbasher** [nomomo/Twitch-Auto-Max-Quality#11]
Seems like option 1 doesn't work on VODs anymore. Tried with both 'Type 0' and 'Type 1'. The VOD tries to load, shows a duration of 00:00:00 and then shows "There was a network error. Please try again. (Error #2000)".

Script still works fully with options 2 and 3 as far as I can tell, just thought I would report about option 1.

**Comment by nomomo** [comment]
I changed some logic in version 0.3.1, I didn't consider it for VOD pages. This is fixed in version 0.3.2, so please update the script. thanks!
