### ISSUE TITLE
The word Source isn't showing up next to the resolution anymore

### ISSUE THREAD

**Issue by thinkpad4** [nomomo/Twitch-Auto-Max-Quality#12]
@nomomo On the latest version of the script, it only shows as 1080P60 not 1080P60 (Source)

**Comment by nomomo** [comment]
I changed some logic in version 0.3.1. TAMQ script now tricks the Twitch player by pretending that the highest quality is not the source quality. I added a regacy option to "Only source quality method". If you want to see the "(source)" text as in version 0.2.2, use regacy option.

**Comment by thinkpad4** [comment]
Thank you very much
