### ISSUE TITLE
When switching between tabs quality lowers

### ISSUE THREAD

**Issue by pottersfield** [nomomo/Twitch-Auto-Max-Quality#16]
Hi,

I am using the latest version of your script and when I switch tabs between Twitch and something else and then go back to twitch the quality is always lower and not the maximum as when I initially launch/open Twitch. So the script does not seem to "update" the max quality when the tab is back on the foreground and "loaded" from the memory. 

I am using your script on my Mac with macOS 14.3.1 on Safari with UserScripts. 

Thx in advance for any assistance

**Comment by nomomo** [comment]
hi. I'm Korean and Twitch is pulling out of Korea, so I don't plan to maintain this script anymore.
If you set it to "Only the quality you want method" in the script settings, there is only one video quality to choose from, so even if tab is disabled, the desired video quality will be maintained. Try this option.

**Comment by pottersfield** [comment]
Ah okay, now I see what you mean. I previously used the app "userscripts" instead of Tampermonkey, so I was not able find the settings menu. Set it now now to only quality I want method.

Thanks!
