### ISSUE TITLE
Bug With Time bar 

### ISSUE THREAD

**Issue by MonkeyDMax92** [nomomo/Twitch-Auto-Max-Quality#6]
Hi,
 your script is unfortunately bugging the VOD's timeline as you can see on the video [here (dailymotion.com)](https://www.dailymotion.com/video/x846oon) (Password: Bug)

**Comment by nomomo** [comment]
Thanks for the report! There was a bug in version 0.1.1 that was fixed for Violentmonkey support.
Update version 0.1.2 from the link below.
https://raw.githubusercontent.com/nomomo/Twitch-Auto-Max-Quality/master/Twitch-Auto-Max-Quality.user.js
